// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.31.0
// 	protoc        v4.23.4
// source: proto/litetable_operation.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type QueryType int32

const (
	QueryType_EXACT  QueryType = 0 // row_key is an exact key
	QueryType_PREFIX QueryType = 1 // row_key is a prefix to match
	QueryType_REGEX  QueryType = 2 // row_key is a regex to match
)

// Enum value maps for QueryType.
var (
	QueryType_name = map[int32]string{
		0: "EXACT",
		1: "PREFIX",
		2: "REGEX",
	}
	QueryType_value = map[string]int32{
		"EXACT":  0,
		"PREFIX": 1,
		"REGEX":  2,
	}
)

func (x QueryType) Enum() *QueryType {
	p := new(QueryType)
	*p = x
	return p
}

func (x QueryType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (QueryType) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_litetable_operation_proto_enumTypes[0].Descriptor()
}

func (QueryType) Type() protoreflect.EnumType {
	return &file_proto_litetable_operation_proto_enumTypes[0]
}

func (x QueryType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use QueryType.Descriptor instead.
func (QueryType) EnumDescriptor() ([]byte, []int) {
	return file_proto_litetable_operation_proto_rawDescGZIP(), []int{0}
}

type Empty struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *Empty) Reset() {
	*x = Empty{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_litetable_operation_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Empty) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Empty) ProtoMessage() {}

func (x *Empty) ProtoReflect() protoreflect.Message {
	mi := &file_proto_litetable_operation_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Empty.ProtoReflect.Descriptor instead.
func (*Empty) Descriptor() ([]byte, []int) {
	return file_proto_litetable_operation_proto_rawDescGZIP(), []int{0}
}

// Represents a timestamped value with optional expiration and tombstone flag.
type TimestampedValue struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Value         []byte `protobuf:"bytes,1,opt,name=value,proto3" json:"value,omitempty"`
	TimestampUnix int64  `protobuf:"varint,2,opt,name=timestamp_unix,json=timestampUnix,proto3" json:"timestamp_unix,omitempty"`
	Tombstone     bool   `protobuf:"varint,3,opt,name=tombstone,proto3" json:"tombstone,omitempty"`
	ExpiresAtUnix int64  `protobuf:"varint,4,opt,name=expires_at_unix,json=expiresAtUnix,proto3" json:"expires_at_unix,omitempty"`
}

func (x *TimestampedValue) Reset() {
	*x = TimestampedValue{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_litetable_operation_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TimestampedValue) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TimestampedValue) ProtoMessage() {}

func (x *TimestampedValue) ProtoReflect() protoreflect.Message {
	mi := &file_proto_litetable_operation_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TimestampedValue.ProtoReflect.Descriptor instead.
func (*TimestampedValue) Descriptor() ([]byte, []int) {
	return file_proto_litetable_operation_proto_rawDescGZIP(), []int{1}
}

func (x *TimestampedValue) GetValue() []byte {
	if x != nil {
		return x.Value
	}
	return nil
}

func (x *TimestampedValue) GetTimestampUnix() int64 {
	if x != nil {
		return x.TimestampUnix
	}
	return 0
}

func (x *TimestampedValue) GetTombstone() bool {
	if x != nil {
		return x.Tombstone
	}
	return false
}

func (x *TimestampedValue) GetExpiresAtUnix() int64 {
	if x != nil {
		return x.ExpiresAtUnix
	}
	return 0
}

// A map of qualifier → repeated timestamped values.
// Equivalent to: map<string, []TimestampedValue>
type VersionedQualifier struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Qualifiers map[string]*QualifierValues `protobuf:"bytes,1,rep,name=qualifiers,proto3" json:"qualifiers,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
}

func (x *VersionedQualifier) Reset() {
	*x = VersionedQualifier{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_litetable_operation_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *VersionedQualifier) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VersionedQualifier) ProtoMessage() {}

func (x *VersionedQualifier) ProtoReflect() protoreflect.Message {
	mi := &file_proto_litetable_operation_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VersionedQualifier.ProtoReflect.Descriptor instead.
func (*VersionedQualifier) Descriptor() ([]byte, []int) {
	return file_proto_litetable_operation_proto_rawDescGZIP(), []int{2}
}

func (x *VersionedQualifier) GetQualifiers() map[string]*QualifierValues {
	if x != nil {
		return x.Qualifiers
	}
	return nil
}

type QualifierValues struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Values []*TimestampedValue `protobuf:"bytes,1,rep,name=values,proto3" json:"values,omitempty"`
}

func (x *QualifierValues) Reset() {
	*x = QualifierValues{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_litetable_operation_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *QualifierValues) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QualifierValues) ProtoMessage() {}

func (x *QualifierValues) ProtoReflect() protoreflect.Message {
	mi := &file_proto_litetable_operation_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QualifierValues.ProtoReflect.Descriptor instead.
func (*QualifierValues) Descriptor() ([]byte, []int) {
	return file_proto_litetable_operation_proto_rawDescGZIP(), []int{3}
}

func (x *QualifierValues) GetValues() []*TimestampedValue {
	if x != nil {
		return x.Values
	}
	return nil
}

// A row of LiteTable data: key + column families and their versioned values.
type Row struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Key  string                         `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Cols map[string]*VersionedQualifier `protobuf:"bytes,2,rep,name=cols,proto3" json:"cols,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"` // family → VersionedQualifier
}

func (x *Row) Reset() {
	*x = Row{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_litetable_operation_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Row) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Row) ProtoMessage() {}

func (x *Row) ProtoReflect() protoreflect.Message {
	mi := &file_proto_litetable_operation_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Row.ProtoReflect.Descriptor instead.
func (*Row) Descriptor() ([]byte, []int) {
	return file_proto_litetable_operation_proto_rawDescGZIP(), []int{4}
}

func (x *Row) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *Row) GetCols() map[string]*VersionedQualifier {
	if x != nil {
		return x.Cols
	}
	return nil
}

// The full Litetable Data schema:
//
//	{
//	 "rows": {
//	   "champ:1": {
//	     "key": "champ:1",
//	     "cols": {
//	       "wrestlers": { // column family
//	         "qualifiers": {
//	           "name": [ // column qualifier
//	             {
//	               "value": "John",
//	               "timestamp": 1234567890,
//	               "expires_at": 1234567890
//	             }
//	           ],
//	           "nickname": [ // column qualifier
//	             {
//	             "value": "Smith",
//	             "timestamp": 1234567890,
//	             "expires_at": 1234567890
//	             }
//	           ],
//	         }
//	       }
//	     }
//	   }
//	 }
//	}
type LitetableData struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Rows map[string]*Row `protobuf:"bytes,1,rep,name=rows,proto3" json:"rows,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
}

func (x *LitetableData) Reset() {
	*x = LitetableData{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_litetable_operation_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LitetableData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LitetableData) ProtoMessage() {}

func (x *LitetableData) ProtoReflect() protoreflect.Message {
	mi := &file_proto_litetable_operation_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LitetableData.ProtoReflect.Descriptor instead.
func (*LitetableData) Descriptor() ([]byte, []int) {
	return file_proto_litetable_operation_proto_rawDescGZIP(), []int{5}
}

func (x *LitetableData) GetRows() map[string]*Row {
	if x != nil {
		return x.Rows
	}
	return nil
}

// ReadRequest is the contract for queries.
//
//	{
//	 "row_key": "champ:1",
//	 "query_type": "EXACT",
//	 "family": "wrestlers",
//	 "qualifiers": ["name", "nickname"],
//	 "latest": 1
//	}
type ReadRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	RowKey     string    `protobuf:"bytes,1,opt,name=row_key,json=rowKey,proto3" json:"row_key,omitempty"`                                              // either exact, prefix, or regex depending on query_type
	QueryType  QueryType `protobuf:"varint,2,opt,name=query_type,json=queryType,proto3,enum=litetable.server.v1.QueryType" json:"query_type,omitempty"` // determines how row_key should be interpreted
	Family     string    `protobuf:"bytes,3,opt,name=family,proto3" json:"family,omitempty"`                                                            // column family
	Qualifiers []string  `protobuf:"bytes,4,rep,name=qualifiers,proto3" json:"qualifiers,omitempty"`                                                    // specific qualifiers
	Latest     int32     `protobuf:"varint,5,opt,name=latest,proto3" json:"latest,omitempty"`                                                           // how many latest values to return per qualifier
}

func (x *ReadRequest) Reset() {
	*x = ReadRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_litetable_operation_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ReadRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReadRequest) ProtoMessage() {}

func (x *ReadRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_litetable_operation_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReadRequest.ProtoReflect.Descriptor instead.
func (*ReadRequest) Descriptor() ([]byte, []int) {
	return file_proto_litetable_operation_proto_rawDescGZIP(), []int{6}
}

func (x *ReadRequest) GetRowKey() string {
	if x != nil {
		return x.RowKey
	}
	return ""
}

func (x *ReadRequest) GetQueryType() QueryType {
	if x != nil {
		return x.QueryType
	}
	return QueryType_EXACT
}

func (x *ReadRequest) GetFamily() string {
	if x != nil {
		return x.Family
	}
	return ""
}

func (x *ReadRequest) GetQualifiers() []string {
	if x != nil {
		return x.Qualifiers
	}
	return nil
}

func (x *ReadRequest) GetLatest() int32 {
	if x != nil {
		return x.Latest
	}
	return 0
}

// ColumnQualifier is a key-value pair representing a column qualifier and its value.
type ColumnQualifier struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name  string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`   // column qualifier
	Value []byte `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"` // value of the column qualifier
}

func (x *ColumnQualifier) Reset() {
	*x = ColumnQualifier{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_litetable_operation_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ColumnQualifier) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ColumnQualifier) ProtoMessage() {}

func (x *ColumnQualifier) ProtoReflect() protoreflect.Message {
	mi := &file_proto_litetable_operation_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ColumnQualifier.ProtoReflect.Descriptor instead.
func (*ColumnQualifier) Descriptor() ([]byte, []int) {
	return file_proto_litetable_operation_proto_rawDescGZIP(), []int{7}
}

func (x *ColumnQualifier) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ColumnQualifier) GetValue() []byte {
	if x != nil {
		return x.Value
	}
	return nil
}

// WriteRequest is the contract for litetable writes.
type WriteRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	RowKey     string             `protobuf:"bytes,1,opt,name=row_key,json=rowKey,proto3" json:"row_key,omitempty"`
	Family     string             `protobuf:"bytes,2,opt,name=family,proto3" json:"family,omitempty"`         // column family
	Qualifiers []*ColumnQualifier `protobuf:"bytes,3,rep,name=qualifiers,proto3" json:"qualifiers,omitempty"` // specific qualifiers
}

func (x *WriteRequest) Reset() {
	*x = WriteRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_litetable_operation_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *WriteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WriteRequest) ProtoMessage() {}

func (x *WriteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_litetable_operation_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WriteRequest.ProtoReflect.Descriptor instead.
func (*WriteRequest) Descriptor() ([]byte, []int) {
	return file_proto_litetable_operation_proto_rawDescGZIP(), []int{8}
}

func (x *WriteRequest) GetRowKey() string {
	if x != nil {
		return x.RowKey
	}
	return ""
}

func (x *WriteRequest) GetFamily() string {
	if x != nil {
		return x.Family
	}
	return ""
}

func (x *WriteRequest) GetQualifiers() []*ColumnQualifier {
	if x != nil {
		return x.Qualifiers
	}
	return nil
}

type DeleteRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	RowKey        string   `protobuf:"bytes,1,opt,name=row_key,json=rowKey,proto3" json:"row_key,omitempty"`
	Family        string   `protobuf:"bytes,2,opt,name=family,proto3" json:"family,omitempty"`                                     // column family
	Qualifiers    []string `protobuf:"bytes,3,rep,name=qualifiers,proto3" json:"qualifiers,omitempty"`                             // specific qualifiers
	TimestampUnix int64    `protobuf:"varint,4,opt,name=timestamp_unix,json=timestampUnix,proto3" json:"timestamp_unix,omitempty"` // (optional) timestamp for the delete operation
	Ttl           int32    `protobuf:"varint,5,opt,name=ttl,proto3" json:"ttl,omitempty"`                                          // (optional) time-to-live in seconds for the delete operation
}

func (x *DeleteRequest) Reset() {
	*x = DeleteRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_litetable_operation_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeleteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteRequest) ProtoMessage() {}

func (x *DeleteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_litetable_operation_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteRequest.ProtoReflect.Descriptor instead.
func (*DeleteRequest) Descriptor() ([]byte, []int) {
	return file_proto_litetable_operation_proto_rawDescGZIP(), []int{9}
}

func (x *DeleteRequest) GetRowKey() string {
	if x != nil {
		return x.RowKey
	}
	return ""
}

func (x *DeleteRequest) GetFamily() string {
	if x != nil {
		return x.Family
	}
	return ""
}

func (x *DeleteRequest) GetQualifiers() []string {
	if x != nil {
		return x.Qualifiers
	}
	return nil
}

func (x *DeleteRequest) GetTimestampUnix() int64 {
	if x != nil {
		return x.TimestampUnix
	}
	return 0
}

func (x *DeleteRequest) GetTtl() int32 {
	if x != nil {
		return x.Ttl
	}
	return 0
}

var File_proto_litetable_operation_proto protoreflect.FileDescriptor

var file_proto_litetable_operation_proto_rawDesc = []byte{
	0x0a, 0x1f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x6c, 0x69, 0x74, 0x65, 0x74, 0x61, 0x62, 0x6c,
	0x65, 0x5f, 0x6f, 0x70, 0x65, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x12, 0x13, 0x6c, 0x69, 0x74, 0x65, 0x74, 0x61, 0x62, 0x6c, 0x65, 0x2e, 0x73, 0x65, 0x72,
	0x76, 0x65, 0x72, 0x2e, 0x76, 0x31, 0x22, 0x07, 0x0a, 0x05, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x22,
	0x95, 0x01, 0x0a, 0x10, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x65, 0x64, 0x56,
	0x61, 0x6c, 0x75, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x0c, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x12, 0x25, 0x0a, 0x0e, 0x74, 0x69,
	0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x5f, 0x75, 0x6e, 0x69, 0x78, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x03, 0x52, 0x0d, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x55, 0x6e, 0x69,
	0x78, 0x12, 0x1c, 0x0a, 0x09, 0x74, 0x6f, 0x6d, 0x62, 0x73, 0x74, 0x6f, 0x6e, 0x65, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x08, 0x52, 0x09, 0x74, 0x6f, 0x6d, 0x62, 0x73, 0x74, 0x6f, 0x6e, 0x65, 0x12,
	0x26, 0x0a, 0x0f, 0x65, 0x78, 0x70, 0x69, 0x72, 0x65, 0x73, 0x5f, 0x61, 0x74, 0x5f, 0x75, 0x6e,
	0x69, 0x78, 0x18, 0x04, 0x20, 0x01, 0x28, 0x03, 0x52, 0x0d, 0x65, 0x78, 0x70, 0x69, 0x72, 0x65,
	0x73, 0x41, 0x74, 0x55, 0x6e, 0x69, 0x78, 0x22, 0xd2, 0x01, 0x0a, 0x12, 0x56, 0x65, 0x72, 0x73,
	0x69, 0x6f, 0x6e, 0x65, 0x64, 0x51, 0x75, 0x61, 0x6c, 0x69, 0x66, 0x69, 0x65, 0x72, 0x12, 0x57,
	0x0a, 0x0a, 0x71, 0x75, 0x61, 0x6c, 0x69, 0x66, 0x69, 0x65, 0x72, 0x73, 0x18, 0x01, 0x20, 0x03,
	0x28, 0x0b, 0x32, 0x37, 0x2e, 0x6c, 0x69, 0x74, 0x65, 0x74, 0x61, 0x62, 0x6c, 0x65, 0x2e, 0x73,
	0x65, 0x72, 0x76, 0x65, 0x72, 0x2e, 0x76, 0x31, 0x2e, 0x56, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e,
	0x65, 0x64, 0x51, 0x75, 0x61, 0x6c, 0x69, 0x66, 0x69, 0x65, 0x72, 0x2e, 0x51, 0x75, 0x61, 0x6c,
	0x69, 0x66, 0x69, 0x65, 0x72, 0x73, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x52, 0x0a, 0x71, 0x75, 0x61,
	0x6c, 0x69, 0x66, 0x69, 0x65, 0x72, 0x73, 0x1a, 0x63, 0x0a, 0x0f, 0x51, 0x75, 0x61, 0x6c, 0x69,
	0x66, 0x69, 0x65, 0x72, 0x73, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65,
	0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6b, 0x65, 0x79, 0x12, 0x3a, 0x0a, 0x05,
	0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x24, 0x2e, 0x6c, 0x69,
	0x74, 0x65, 0x74, 0x61, 0x62, 0x6c, 0x65, 0x2e, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x2e, 0x76,
	0x31, 0x2e, 0x51, 0x75, 0x61, 0x6c, 0x69, 0x66, 0x69, 0x65, 0x72, 0x56, 0x61, 0x6c, 0x75, 0x65,
	0x73, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x3a, 0x02, 0x38, 0x01, 0x22, 0x50, 0x0a, 0x0f,
	0x51, 0x75, 0x61, 0x6c, 0x69, 0x66, 0x69, 0x65, 0x72, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x73, 0x12,
	0x3d, 0x0a, 0x06, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32,
	0x25, 0x2e, 0x6c, 0x69, 0x74, 0x65, 0x74, 0x61, 0x62, 0x6c, 0x65, 0x2e, 0x73, 0x65, 0x72, 0x76,
	0x65, 0x72, 0x2e, 0x76, 0x31, 0x2e, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x65,
	0x64, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x52, 0x06, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x73, 0x22, 0xb1,
	0x01, 0x0a, 0x03, 0x52, 0x6f, 0x77, 0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x03, 0x6b, 0x65, 0x79, 0x12, 0x36, 0x0a, 0x04, 0x63, 0x6f, 0x6c, 0x73,
	0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x22, 0x2e, 0x6c, 0x69, 0x74, 0x65, 0x74, 0x61, 0x62,
	0x6c, 0x65, 0x2e, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x2e, 0x76, 0x31, 0x2e, 0x52, 0x6f, 0x77,
	0x2e, 0x43, 0x6f, 0x6c, 0x73, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x52, 0x04, 0x63, 0x6f, 0x6c, 0x73,
	0x1a, 0x60, 0x0a, 0x09, 0x43, 0x6f, 0x6c, 0x73, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x12, 0x10, 0x0a,
	0x03, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6b, 0x65, 0x79, 0x12,
	0x3d, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x27,
	0x2e, 0x6c, 0x69, 0x74, 0x65, 0x74, 0x61, 0x62, 0x6c, 0x65, 0x2e, 0x73, 0x65, 0x72, 0x76, 0x65,
	0x72, 0x2e, 0x76, 0x31, 0x2e, 0x56, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x65, 0x64, 0x51, 0x75,
	0x61, 0x6c, 0x69, 0x66, 0x69, 0x65, 0x72, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x3a, 0x02,
	0x38, 0x01, 0x22, 0xa4, 0x01, 0x0a, 0x0d, 0x4c, 0x69, 0x74, 0x65, 0x74, 0x61, 0x62, 0x6c, 0x65,
	0x44, 0x61, 0x74, 0x61, 0x12, 0x40, 0x0a, 0x04, 0x72, 0x6f, 0x77, 0x73, 0x18, 0x01, 0x20, 0x03,
	0x28, 0x0b, 0x32, 0x2c, 0x2e, 0x6c, 0x69, 0x74, 0x65, 0x74, 0x61, 0x62, 0x6c, 0x65, 0x2e, 0x73,
	0x65, 0x72, 0x76, 0x65, 0x72, 0x2e, 0x76, 0x31, 0x2e, 0x4c, 0x69, 0x74, 0x65, 0x74, 0x61, 0x62,
	0x6c, 0x65, 0x44, 0x61, 0x74, 0x61, 0x2e, 0x52, 0x6f, 0x77, 0x73, 0x45, 0x6e, 0x74, 0x72, 0x79,
	0x52, 0x04, 0x72, 0x6f, 0x77, 0x73, 0x1a, 0x51, 0x0a, 0x09, 0x52, 0x6f, 0x77, 0x73, 0x45, 0x6e,
	0x74, 0x72, 0x79, 0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x03, 0x6b, 0x65, 0x79, 0x12, 0x2e, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x18, 0x2e, 0x6c, 0x69, 0x74, 0x65, 0x74, 0x61, 0x62, 0x6c, 0x65,
	0x2e, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x2e, 0x76, 0x31, 0x2e, 0x52, 0x6f, 0x77, 0x52, 0x05,
	0x76, 0x61, 0x6c, 0x75, 0x65, 0x3a, 0x02, 0x38, 0x01, 0x22, 0xb5, 0x01, 0x0a, 0x0b, 0x52, 0x65,
	0x61, 0x64, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x17, 0x0a, 0x07, 0x72, 0x6f, 0x77,
	0x5f, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x72, 0x6f, 0x77, 0x4b,
	0x65, 0x79, 0x12, 0x3d, 0x0a, 0x0a, 0x71, 0x75, 0x65, 0x72, 0x79, 0x5f, 0x74, 0x79, 0x70, 0x65,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x1e, 0x2e, 0x6c, 0x69, 0x74, 0x65, 0x74, 0x61, 0x62,
	0x6c, 0x65, 0x2e, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x2e, 0x76, 0x31, 0x2e, 0x51, 0x75, 0x65,
	0x72, 0x79, 0x54, 0x79, 0x70, 0x65, 0x52, 0x09, 0x71, 0x75, 0x65, 0x72, 0x79, 0x54, 0x79, 0x70,
	0x65, 0x12, 0x16, 0x0a, 0x06, 0x66, 0x61, 0x6d, 0x69, 0x6c, 0x79, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x06, 0x66, 0x61, 0x6d, 0x69, 0x6c, 0x79, 0x12, 0x1e, 0x0a, 0x0a, 0x71, 0x75, 0x61,
	0x6c, 0x69, 0x66, 0x69, 0x65, 0x72, 0x73, 0x18, 0x04, 0x20, 0x03, 0x28, 0x09, 0x52, 0x0a, 0x71,
	0x75, 0x61, 0x6c, 0x69, 0x66, 0x69, 0x65, 0x72, 0x73, 0x12, 0x16, 0x0a, 0x06, 0x6c, 0x61, 0x74,
	0x65, 0x73, 0x74, 0x18, 0x05, 0x20, 0x01, 0x28, 0x05, 0x52, 0x06, 0x6c, 0x61, 0x74, 0x65, 0x73,
	0x74, 0x22, 0x3b, 0x0a, 0x0f, 0x43, 0x6f, 0x6c, 0x75, 0x6d, 0x6e, 0x51, 0x75, 0x61, 0x6c, 0x69,
	0x66, 0x69, 0x65, 0x72, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75,
	0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x22, 0x85,
	0x01, 0x0a, 0x0c, 0x57, 0x72, 0x69, 0x74, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12,
	0x17, 0x0a, 0x07, 0x72, 0x6f, 0x77, 0x5f, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x06, 0x72, 0x6f, 0x77, 0x4b, 0x65, 0x79, 0x12, 0x16, 0x0a, 0x06, 0x66, 0x61, 0x6d, 0x69,
	0x6c, 0x79, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x66, 0x61, 0x6d, 0x69, 0x6c, 0x79,
	0x12, 0x44, 0x0a, 0x0a, 0x71, 0x75, 0x61, 0x6c, 0x69, 0x66, 0x69, 0x65, 0x72, 0x73, 0x18, 0x03,
	0x20, 0x03, 0x28, 0x0b, 0x32, 0x24, 0x2e, 0x6c, 0x69, 0x74, 0x65, 0x74, 0x61, 0x62, 0x6c, 0x65,
	0x2e, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x2e, 0x76, 0x31, 0x2e, 0x43, 0x6f, 0x6c, 0x75, 0x6d,
	0x6e, 0x51, 0x75, 0x61, 0x6c, 0x69, 0x66, 0x69, 0x65, 0x72, 0x52, 0x0a, 0x71, 0x75, 0x61, 0x6c,
	0x69, 0x66, 0x69, 0x65, 0x72, 0x73, 0x22, 0x99, 0x01, 0x0a, 0x0d, 0x44, 0x65, 0x6c, 0x65, 0x74,
	0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x17, 0x0a, 0x07, 0x72, 0x6f, 0x77, 0x5f,
	0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x72, 0x6f, 0x77, 0x4b, 0x65,
	0x79, 0x12, 0x16, 0x0a, 0x06, 0x66, 0x61, 0x6d, 0x69, 0x6c, 0x79, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x06, 0x66, 0x61, 0x6d, 0x69, 0x6c, 0x79, 0x12, 0x1e, 0x0a, 0x0a, 0x71, 0x75, 0x61,
	0x6c, 0x69, 0x66, 0x69, 0x65, 0x72, 0x73, 0x18, 0x03, 0x20, 0x03, 0x28, 0x09, 0x52, 0x0a, 0x71,
	0x75, 0x61, 0x6c, 0x69, 0x66, 0x69, 0x65, 0x72, 0x73, 0x12, 0x25, 0x0a, 0x0e, 0x74, 0x69, 0x6d,
	0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x5f, 0x75, 0x6e, 0x69, 0x78, 0x18, 0x04, 0x20, 0x01, 0x28,
	0x03, 0x52, 0x0d, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x55, 0x6e, 0x69, 0x78,
	0x12, 0x10, 0x0a, 0x03, 0x74, 0x74, 0x6c, 0x18, 0x05, 0x20, 0x01, 0x28, 0x05, 0x52, 0x03, 0x74,
	0x74, 0x6c, 0x2a, 0x2d, 0x0a, 0x09, 0x51, 0x75, 0x65, 0x72, 0x79, 0x54, 0x79, 0x70, 0x65, 0x12,
	0x09, 0x0a, 0x05, 0x45, 0x58, 0x41, 0x43, 0x54, 0x10, 0x00, 0x12, 0x0a, 0x0a, 0x06, 0x50, 0x52,
	0x45, 0x46, 0x49, 0x58, 0x10, 0x01, 0x12, 0x09, 0x0a, 0x05, 0x52, 0x45, 0x47, 0x45, 0x58, 0x10,
	0x02, 0x32, 0xfa, 0x01, 0x0a, 0x10, 0x4c, 0x69, 0x74, 0x65, 0x74, 0x61, 0x62, 0x6c, 0x65, 0x53,
	0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x4c, 0x0a, 0x04, 0x52, 0x65, 0x61, 0x64, 0x12, 0x20,
	0x2e, 0x6c, 0x69, 0x74, 0x65, 0x74, 0x61, 0x62, 0x6c, 0x65, 0x2e, 0x73, 0x65, 0x72, 0x76, 0x65,
	0x72, 0x2e, 0x76, 0x31, 0x2e, 0x52, 0x65, 0x61, 0x64, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x1a, 0x22, 0x2e, 0x6c, 0x69, 0x74, 0x65, 0x74, 0x61, 0x62, 0x6c, 0x65, 0x2e, 0x73, 0x65, 0x72,
	0x76, 0x65, 0x72, 0x2e, 0x76, 0x31, 0x2e, 0x4c, 0x69, 0x74, 0x65, 0x74, 0x61, 0x62, 0x6c, 0x65,
	0x44, 0x61, 0x74, 0x61, 0x12, 0x4e, 0x0a, 0x05, 0x57, 0x72, 0x69, 0x74, 0x65, 0x12, 0x21, 0x2e,
	0x6c, 0x69, 0x74, 0x65, 0x74, 0x61, 0x62, 0x6c, 0x65, 0x2e, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72,
	0x2e, 0x76, 0x31, 0x2e, 0x57, 0x72, 0x69, 0x74, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x1a, 0x22, 0x2e, 0x6c, 0x69, 0x74, 0x65, 0x74, 0x61, 0x62, 0x6c, 0x65, 0x2e, 0x73, 0x65, 0x72,
	0x76, 0x65, 0x72, 0x2e, 0x76, 0x31, 0x2e, 0x4c, 0x69, 0x74, 0x65, 0x74, 0x61, 0x62, 0x6c, 0x65,
	0x44, 0x61, 0x74, 0x61, 0x12, 0x48, 0x0a, 0x06, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x12, 0x22,
	0x2e, 0x6c, 0x69, 0x74, 0x65, 0x74, 0x61, 0x62, 0x6c, 0x65, 0x2e, 0x73, 0x65, 0x72, 0x76, 0x65,
	0x72, 0x2e, 0x76, 0x31, 0x2e, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x1a, 0x1a, 0x2e, 0x6c, 0x69, 0x74, 0x65, 0x74, 0x61, 0x62, 0x6c, 0x65, 0x2e, 0x73,
	0x65, 0x72, 0x76, 0x65, 0x72, 0x2e, 0x76, 0x31, 0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x42, 0x11,
	0x5a, 0x0f, 0x70, 0x6b, 0x67, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x3b, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_proto_litetable_operation_proto_rawDescOnce sync.Once
	file_proto_litetable_operation_proto_rawDescData = file_proto_litetable_operation_proto_rawDesc
)

func file_proto_litetable_operation_proto_rawDescGZIP() []byte {
	file_proto_litetable_operation_proto_rawDescOnce.Do(func() {
		file_proto_litetable_operation_proto_rawDescData = protoimpl.X.CompressGZIP(file_proto_litetable_operation_proto_rawDescData)
	})
	return file_proto_litetable_operation_proto_rawDescData
}

var file_proto_litetable_operation_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_proto_litetable_operation_proto_msgTypes = make([]protoimpl.MessageInfo, 13)
var file_proto_litetable_operation_proto_goTypes = []interface{}{
	(QueryType)(0),             // 0: litetable.server.v1.QueryType
	(*Empty)(nil),              // 1: litetable.server.v1.Empty
	(*TimestampedValue)(nil),   // 2: litetable.server.v1.TimestampedValue
	(*VersionedQualifier)(nil), // 3: litetable.server.v1.VersionedQualifier
	(*QualifierValues)(nil),    // 4: litetable.server.v1.QualifierValues
	(*Row)(nil),                // 5: litetable.server.v1.Row
	(*LitetableData)(nil),      // 6: litetable.server.v1.LitetableData
	(*ReadRequest)(nil),        // 7: litetable.server.v1.ReadRequest
	(*ColumnQualifier)(nil),    // 8: litetable.server.v1.ColumnQualifier
	(*WriteRequest)(nil),       // 9: litetable.server.v1.WriteRequest
	(*DeleteRequest)(nil),      // 10: litetable.server.v1.DeleteRequest
	nil,                        // 11: litetable.server.v1.VersionedQualifier.QualifiersEntry
	nil,                        // 12: litetable.server.v1.Row.ColsEntry
	nil,                        // 13: litetable.server.v1.LitetableData.RowsEntry
}
var file_proto_litetable_operation_proto_depIdxs = []int32{
	11, // 0: litetable.server.v1.VersionedQualifier.qualifiers:type_name -> litetable.server.v1.VersionedQualifier.QualifiersEntry
	2,  // 1: litetable.server.v1.QualifierValues.values:type_name -> litetable.server.v1.TimestampedValue
	12, // 2: litetable.server.v1.Row.cols:type_name -> litetable.server.v1.Row.ColsEntry
	13, // 3: litetable.server.v1.LitetableData.rows:type_name -> litetable.server.v1.LitetableData.RowsEntry
	0,  // 4: litetable.server.v1.ReadRequest.query_type:type_name -> litetable.server.v1.QueryType
	8,  // 5: litetable.server.v1.WriteRequest.qualifiers:type_name -> litetable.server.v1.ColumnQualifier
	4,  // 6: litetable.server.v1.VersionedQualifier.QualifiersEntry.value:type_name -> litetable.server.v1.QualifierValues
	3,  // 7: litetable.server.v1.Row.ColsEntry.value:type_name -> litetable.server.v1.VersionedQualifier
	5,  // 8: litetable.server.v1.LitetableData.RowsEntry.value:type_name -> litetable.server.v1.Row
	7,  // 9: litetable.server.v1.LitetableService.Read:input_type -> litetable.server.v1.ReadRequest
	9,  // 10: litetable.server.v1.LitetableService.Write:input_type -> litetable.server.v1.WriteRequest
	10, // 11: litetable.server.v1.LitetableService.Delete:input_type -> litetable.server.v1.DeleteRequest
	6,  // 12: litetable.server.v1.LitetableService.Read:output_type -> litetable.server.v1.LitetableData
	6,  // 13: litetable.server.v1.LitetableService.Write:output_type -> litetable.server.v1.LitetableData
	1,  // 14: litetable.server.v1.LitetableService.Delete:output_type -> litetable.server.v1.Empty
	12, // [12:15] is the sub-list for method output_type
	9,  // [9:12] is the sub-list for method input_type
	9,  // [9:9] is the sub-list for extension type_name
	9,  // [9:9] is the sub-list for extension extendee
	0,  // [0:9] is the sub-list for field type_name
}

func init() { file_proto_litetable_operation_proto_init() }
func file_proto_litetable_operation_proto_init() {
	if File_proto_litetable_operation_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_proto_litetable_operation_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Empty); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_litetable_operation_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TimestampedValue); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_litetable_operation_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*VersionedQualifier); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_litetable_operation_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*QualifierValues); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_litetable_operation_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Row); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_litetable_operation_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*LitetableData); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_litetable_operation_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ReadRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_litetable_operation_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ColumnQualifier); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_litetable_operation_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*WriteRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_litetable_operation_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeleteRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_proto_litetable_operation_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   13,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_litetable_operation_proto_goTypes,
		DependencyIndexes: file_proto_litetable_operation_proto_depIdxs,
		EnumInfos:         file_proto_litetable_operation_proto_enumTypes,
		MessageInfos:      file_proto_litetable_operation_proto_msgTypes,
	}.Build()
	File_proto_litetable_operation_proto = out.File
	file_proto_litetable_operation_proto_rawDesc = nil
	file_proto_litetable_operation_proto_goTypes = nil
	file_proto_litetable_operation_proto_depIdxs = nil
}
